# Generated by Django 3.2.23 on 2023-11-23 12:28
import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTask',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'name',
                    models.CharField(max_length=128, verbose_name='Name'),
                ),
                (
                    'start_date',
                    models.DateTimeField(
                        blank=True,
                        default=None,
                        help_text='User task working start date',
                        null=True,
                        verbose_name='Start date',
                    ),
                ),
                (
                    'duration',
                    models.DurationField(
                        blank=True,
                        default=None,
                        help_text='User task working duration',
                        null=True,
                        verbose_name='Duration',
                    ),
                ),
                (
                    'status',
                    models.CharField(
                        choices=[
                            ('PENDING', 'Pending'),
                            ('STARTED', 'Started'),
                            ('RETRY', 'Retry'),
                            ('FAILURE', 'Failure'),
                            ('SUCCESS', 'Success'),
                            ('REVOKED', 'Revoked'),
                        ],
                        default='PENDING',
                        help_text='User task status in the moment',
                        max_length=7,
                        verbose_name='Status',
                    ),
                ),
                (
                    'result_link',
                    models.CharField(
                        blank=True,
                        default=None,
                        help_text='User task result link',
                        max_length=256,
                        null=True,
                        verbose_name='Result link',
                    ),
                ),
                (
                    'start_parameters',
                    models.CharField(
                        help_text='Parameters which will configure the result',
                        max_length=256,
                        verbose_name='Start parameters',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name='user_tasks',
                        related_query_name='user_task',
                        to=settings.AUTH_USER_MODEL,
                        verbose_name='User',
                    ),
                ),
            ],
        ),
    ]
