# Generated by Django 3.2.23 on 2023-11-23 13:17
import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_tasks_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='start_parameters',
            field=django.contrib.postgres.fields.jsonb.JSONField(
                help_text='Parameters which will configure the result',
                verbose_name='Start parameters',
            ),
        ),
    ]
