default_language_version:
  python: python3.7
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: double-quote-string-fixer
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: no-commit-to-branch
        args: [ "--branch", "master", "--branch", "develop" ]
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.3.0
    hooks:
      - id: add-trailing-comma
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.8.3
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/psf/black
    rev: 22.10.0
    hooks:
      - id: black
        language_version: python3.7
        args: [ "--line-length=79", "--skip-string-normalization" ]
        exclude: ^migrations/
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4
    hooks:
      - id: flake8
        additional_dependencies: [
            "flake8-comprehensions",
            "flake8-mutable",
            "flake8-print",
        ]
