# Generated by Django 2.2.7 on 2023-09-23 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('original_currency', models.CharField(max_length=3)),
                ('target_currency', models.CharField(max_length=3)),
                ('value', models.PositiveIntegerField()),
                ('coefficient', models.PositiveIntegerField()),
                ('source', models.CharField(max_length=256)),
                ('source_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
