# Generated by Django 2.2.7 on 2023-09-30 11:49

from django.conf import settings
import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('name', models.CharField(max_length=10, unique=True, verbose_name='Name')),
                ('autoload_method', models.CharField(choices=[('get_cbr_data', 'get_cbr_data'), ('get_ecb_data', 'get_ecb_data')], default='get_cbr_data', help_text='The name of the method used to extract data from the source', max_length=100, verbose_name='Autoload method')),
                ('base_ticker', models.CharField(help_text='Base currency that is used as reference in the source', max_length=3, verbose_name='Base ticker')),
                ('tickers', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=3), default=list, help_text='Tickers that are converted from the base one', size=None, verbose_name='Tickers')),
                ('last_run_result', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='Shows was there any errors in the last run', verbose_name='Last run result')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
        migrations.CreateModel(
            name='Converter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('input_ticker', models.CharField(help_text='The ticker that converted into the base ticker', max_length=3, verbose_name='Input ticker')),
                ('output_ticker', models.CharField(help_text='Actually, the base ticker from the source', max_length=3, verbose_name='Output ticker')),
                ('value', models.FloatField(verbose_name='Value')),
                ('coefficient', models.IntegerField(verbose_name='Coefficient')),
                ('source_date', models.DateTimeField(help_text='The source data date', verbose_name='Source date')),
                ('source', models.ForeignKey(help_text='Source where the currency data was taken', on_delete=django.db.models.deletion.PROTECT, related_name='converters', related_query_name='converter', to='converter.Source', verbose_name='Source')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='converters', related_query_name='converter', to=settings.AUTH_USER_MODEL, verbose_name='Updated by')),
            ],
            options={
                'verbose_name': 'Converter',
                'verbose_name_plural': 'Converters',
            },
        ),
    ]
