# Generated by Django 2.2.7 on 2023-09-23 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='converter',
            name='source_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
