# Generated by Django 2.2.7 on 2023-10-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20230930_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='last_run_time',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='source',
            name='autoload_method',
            field=models.CharField(choices=[('get_cbr_data', 'get_cbr_data'), ('get_ecb_data', 'get_ecb_data'), ('get_nbrb_data', 'get_nbrb_data')], default='get_cbr_data', help_text='The name of the method used to extract data from the source', max_length=100, verbose_name='Autoload method'),
        ),
    ]
