# Generated by Django 2.2.7 on 2023-09-24 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0003_auto_20230923_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='source_date',
            field=models.DateTimeField(),
        ),
    ]
