# Generated by Django 2.2.7 on 2023-10-03 18:15

import converter.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0004_last_run_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='source_date',
            field=models.DateTimeField(help_text='The source data date', validators=[converter.validators.validate_source_date], verbose_name='Source date'),
        ),
    ]
