# Generated by Django 2.2.7 on 2023-10-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0005_last_run_time_and_validator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='value',
            field=models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Value'),
        ),
    ]
