# Generated by Django 2.2.7 on 2023-10-31 16:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('converter', '0006_value_from_float_to_decimal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='converter',
            name='input_ticker',
            field=models.CharField(help_text='The ticker that converting into the base one', max_length=10, verbose_name='Input ticker'),
        ),
        migrations.AlterField(
            model_name='converter',
            name='output_ticker',
            field=models.CharField(help_text='Base currency that is using as reference in the source', max_length=10, verbose_name='Output ticker'),
        ),
        migrations.AlterField(
            model_name='converter',
            name='value',
            field=models.DecimalField(decimal_places=10, max_digits=24, verbose_name='Value'),
        ),
        migrations.AlterField(
            model_name='source',
            name='autoload_method',
            field=models.CharField(choices=[('get_cbr_data', 'get_cbr_data'), ('get_ecb_data', 'get_ecb_data'), ('get_nbrb_data', 'get_nbrb_data'), ('get_binance_data', 'get_binance_data')], default='get_cbr_data', help_text='The name of the method used to extract data from the source', max_length=100, verbose_name='Autoload method'),
        ),
        migrations.AlterField(
            model_name='source',
            name='base_ticker',
            field=models.CharField(help_text='Base currency that is using as reference in the source', max_length=10, verbose_name='Base ticker'),
        ),
        migrations.AlterField(
            model_name='source',
            name='tickers',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), default=list, help_text='Tickers that are converting from the base one', size=None, verbose_name='Tickers'),
        ),
    ]
